version: '3.7'

services:
  jibri:
    build:
      context: .
      dockerfile: ./Dockerfile
    extra_hosts:
      - '${XMPP_DOMAIN}:${XMPP_SERVER}'
    volumes:
      - ${CONFIG}/jibri:/config
      - /dev/shm:/dev/shm
    cap_add:
      - SYS_ADMIN
      - NET_BIND_SERVICE
    devices:
      - /dev/snd:/dev/snd
    restart: unless-stopped
    #command: sh -c "
      #sleep 60000"
    environment:
      - XMPP_AUTH_DOMAIN
      - XMPP_INTERNAL_MUC_DOMAIN
      - XMPP_RECORDER_DOMAIN
      - XMPP_SERVER
      - XMPP_DOMAIN
      - JIBRI_XMPP_USER
      - JIBRI_XMPP_PASSWORD
      - JIBRI_BREWERY_MUC
      - JIBRI_RECORDER_USER
      - JIBRI_RECORDER_PASSWORD
      - JIBRI_RECORDING_DIR
      - JIBRI_FINALIZE_RECORDING_SCRIPT_PATH
      - JIBRI_STRIP_DOMAIN_JID
      - JIBRI_LOGS_DIR
      - CHROMIUM_FLAGS
      - DISPLAY=:0
      - TZ
      - JIBRI_NO_MEDIA_TIMEOUT
      - JIBRI_ALL_MUTED_TIMEOUT
      - JIBRI_DEFAULT_CALL_EMPTY_TIMEOUT
