version: '3.7'

services:
  etherpad:
    build:
      context: ./etherpad
      dockerfile: ./Dockerfile
    environment:
        - TITLE=${ETHERPAD_TITLE}
        - DEFAULT_PAD_TEXT=${ETHERPAD_DEFAULT_PAD_TEXT}
        - SKIN_NAME=${ETHERPAD_SKIN_NAME}
        - SKIN_VARIANTS=${ETHERPAD_SKIN_VARIANTS}
    restart: unless-stopped
    depends_on:
      - prosody
    #ports:
      #- 9001
    networks:
      - confomeetnet

  jibri:
    build:
      context: ./jibri
      dockerfile: ./Dockerfile
    cap_add:
      - SYS_ADMIN
      - NET_BIND_SERVICE
    devices:
      - /dev/snd:/dev/snd
    restart: unless-stopped
    #command: sh -c "
      #sleep 60000"
    environment:
      - XMPP_AUTH_DOMAIN
      - XMPP_INTERNAL_MUC_DOMAIN
      - XMPP_RECORDER_DOMAIN
      - XMPP_SERVER
      - XMPP_DOMAIN
      - JIBRI_XMPP_USER
      - JIBRI_XMPP_PASSWORD
      - JIBRI_BREWERY_MUC
      - JIBRI_RECORDER_USER
      - JIBRI_RECORDER_PASSWORD
      - JIBRI_RECORDING_DIR
      - JIBRI_FINALIZE_RECORDING_SCRIPT_PATH
      - JIBRI_STRIP_DOMAIN_JID
      - JIBRI_LOGS_DIR
      - CHROMIUM_FLAGS
      - DISPLAY=:0
      - TZ
      - JIBRI_NO_MEDIA_TIMEOUT
      - JIBRI_ALL_MUTED_TIMEOUT
      - JIBRI_DEFAULT_CALL_EMPTY_TIMEOUT
      - CONFOMEET_S3_URL
      - CONFOMEET_S3_CLIENT_ID
      - CONFOMEET_S3_CLIENT_SECRET
      - CONFOMEET_S3_REGION
      - CONFOMEET_S3_BUCKET
    extra_hosts:
      - '${XMPP_DOMAIN}:host-gateway'
    networks:
      - confomeetnet
    volumes:
      - ./volume/jibri:/config
      - /dev/shm:/dev/shm

  jicofo:
    build:
      context: ./jicofo
      dockerfile: ./Dockerfile
      args:
        XMPP_DOMAIN: ${XMPP_DOMAIN}
        TZ: ${TZ}
        JICOFO_AUTH_PASSWORD: ${JICOFO_AUTH_PASSWORD}
    depends_on:
      - prosody
    networks:
      - confomeetnet
    restart: unless-stopped

  jvb:
    build:
      context: ./jvb
      dockerfile: ./Dockerfile
      args:
        JVB_PORT: ${JVB_PORT}
        XMPP_DOMAIN: ${XMPP_DOMAIN}
        JVB_USERNAME: ${JVB_USERNAME}
        JVB_MUC_NICKNAME: ${JVB_MUC_NICKNAME}
        JVB_AUTH_NAME: ${JVB_AUTH_NAME}
        JVB_AUTH_PASS: ${JVB_AUTH_PASS}
        JVB_LOCAL_ADDRESS: ${JVB_LOCAL_ADDRESS}
        JVB_PUBLIC_ADDRESS: ${JVB_PUBLIC_ADDRESS}
        STUN_ADDRESSES: ${STUN_ADDRESSES}
    network_mode: host
    restart: unless-stopped

  nginx:
    build:
      context: ./nginx
      dockerfile: ./Dockerfile
      args:
        XMPP_DOMAIN: ${XMPP_DOMAIN}
        ADMIN_FRONTEND_GIT_USER: ${ADMIN_FRONTEND_GIT_USER}
        ADMIN_FRONTEND_GIT_PASS: ${ADMIN_FRONTEND_GIT_PASS}
        ADMIN_FRONTEND_BRANCH: ${ADMIN_FRONTEND_BRANCH}
        CCMS_BASE_URL: ${CCMS_BASE_URL}
    depends_on:
      - jicofo
      - prosody
      - etherpad
      - whiteboard
    ports:
      - '80:80'
      - '443:443'
    networks:
      - confomeetnet
    restart: unless-stopped
    volumes:
      - ./volume/jibri:/config
    extra_hosts:
      - "admin_backend:host-gateway"

  prosody:
    build:
      context: ./prosody
      dockerfile: ./Dockerfile
      args:
        XMPP_DOMAIN: ${XMPP_DOMAIN}
        PROSODY_APP_ID: ${PROSODY_APP_ID}
        PROSODY_APP_SECRET: ${PROSODY_APP_SECRET}
        JICOFO_AUTH_PASSWORD: ${JICOFO_AUTH_PASSWORD}
        JVB_USERNAME: ${JVB_USERNAME}
        JVB_AUTH_PASS: ${JVB_AUTH_PASS}
        JIBRI_RECORDER_PASSWORD: ${JIBRI_RECORDER_PASSWORD}
        JIBRI_XMPP_PASSWORD: ${JIBRI_XMPP_PASSWORD}
        JIGASI_XMPP_USER: ${JIGASI_XMPP_USER}
        JIGASI_XMPP_PASSWORD: ${JIGASI_XMPP_PASSWORD}

    extra_hosts:
      - '${XMPP_DOMAIN}:127.0.0.1'
    #volumes:
      #- ./log:/var/log/prosody
    networks:
      - confomeetnet
    ports:
      - '5222:5222'
      - '5280:5280'
    restart: unless-stopped

  whiteboard:
    build:
      context: ./excalidraw-backend
      dockerfile: ./Dockerfile
    restart: unless-stopped
    #ports:
      #- 9091
      #- 3002
    depends_on:
      - prosody
    networks:
      - confomeetnet

networks:
  confomeetnet:
    driver: bridge
