version: '3.7'

services:
  admin_backend:
    build:
      context: ./admin_backend
      dockerfile: ./Dockerfile
      args:
        ADMIN_FRONTEND_GIT_USER: ${ADMIN_FRONTEND_GIT_USER}
        ADMIN_FRONTEND_GIT_PASS: ${ADMIN_FRONTEND_GIT_PASS}
        ADMIN_BACKEND_BRANCH: ${ADMIN_BACKEND_BRANCH}
    environment:
      ConnectionStrings__DbConnection: ${ADMIN_DB_CONNECTION_STRING}
      Schema: ${ADMIN_DB_SCHEMA}
      DocumentStorage: ${ADMIN_DOCUMENT_STORAGE}
      Meeting__secret: ${PROSODY_APP_SECRET}
      Meeting__iss: ${ADMIN_MEETING_ISS}
      Meeting__aud: ${ADMIN_MEETING_AUD}
      Meeting__host: https://${XMPP_DOMAIN}
      Meeting__sub: ${XMPP_DOMAIN}
      Jwt__Key: ${ADMIN_JWT_KEY}
      Jwt__Issuer: ${ADMIN_JWT_ISSUER}
      Jwt__Audience: ${ADMIN_JWT_AUDIENCE}
      Jwt__TokenInMinutes: ${ADMIN_JWT_TOKENINMINUTES}
      ChannelMailFirstSetting__Mail: ${ADMIN_MAIL_MAIL}
      ChannelMailFirstSetting__DisplayName: ${ADMIN_MAIL_DISPLAYNAME}
      ChannelMailFirstSetting__Password: ${ADMIN_MAIL_PASSWORD}
      ChannelMailFirstSetting__Host: ${ADMIN_MAIL_HOST}
      ChannelMailFirstSetting__Port: ${ADMIN_MAIL_PORT}
      GoogleReCaptchaSecretKey__SecretKey: ${ADMIN_CAPTCHA_SECRET_KEY}
      PassworLifetimeDays: ${ADMIN_PASSWORD_LIFE_TIME_DAYS}
      LockedTempTimeInMinutes: ${ADMIN_LOCKED_TEMP_TIME_IN_MINUTES}
      CurrentHostName: ${ADMIN_CURRENT_HOST_NAME}
      EnableRegistration: ${ADMIN_ENABLE_REGISTRATION}
      EnableOnlyAdminLogin: ${ADMIN_ENABLE_ONLAY_ADMIN_LOGIN}
      ProsodyDomain: ${CONFERENCE_PROSODY_DOMAIN}
      OtpPeriodInMinutes: ${ADMIN_OTP_PERIOD_IN_MINUTES}
      DisableActivate: ${ADMIN_DISABLE_ACTIVE}
      YandexDisk__DebugToken: ${YANDEX_DISK_DEBUG_TOKEN}
      ASPNETCORE_HTTP_PORTS: "5000"
      CONFOMEET_S3_URL: ${CONFOMEET_S3_URL}
      CONFOMEET_S3_URL_OVERRIDE_FOR_AWS_SDK: ${CONFOMEET_S3_URL_OVERRIDE_FOR_AWS_SDK}
      CONFOMEET_S3_CLIENT_ID: ${CONFOMEET_S3_CLIENT_ID}
      CONFOMEET_S3_CLIENT_SECRET: ${CONFOMEET_S3_CLIENT_SECRET}
      CONFOMEET_S3_REGION: ${CONFOMEET_S3_REGION}
      oidc__authority: ${OIDC_AUTHORITY}
      oidc__client_id: ${OIDC_CLIENT_ID}
    networks:
      - confomeetnet
    restart: unless-stopped
    volumes:
      - ./volume/jibri:/config

  etherpad:
    build:
      context: ./etherpad
      dockerfile: ./Dockerfile
    environment:
        - TITLE=${ETHERPAD_TITLE}
        - DEFAULT_PAD_TEXT=${ETHERPAD_DEFAULT_PAD_TEXT}
        - SKIN_NAME=${ETHERPAD_SKIN_NAME}
        - SKIN_VARIANTS=${ETHERPAD_SKIN_VARIANTS}
    restart: unless-stopped
    depends_on:
      - prosody
    #ports:
      #- 9001
    networks:
      - confomeetnet

  jicofo:
    build:
      context: jicofo
      args:
        BASE_TAG: ${JITSI_IMAGE_VERSION}
    restart: ${RESTART_POLICY:-unless-stopped}
    ports:
      - '127.0.0.1:${JICOFO_REST_PORT:-8888}:8888'
    volumes:
      - ${CONFIG}/jicofo:/config:Z
    environment:
      - AUTH_TYPE
      - BRIDGE_AVG_PARTICIPANT_STRESS
      - BRIDGE_STRESS_THRESHOLD
      - ENABLE_AUTH
      - ENABLE_AUTO_OWNER
      - ENABLE_CODEC_VP8
      - ENABLE_CODEC_VP9
      - ENABLE_CODEC_AV1
      - ENABLE_CODEC_H264
      - ENABLE_CODEC_OPUS_RED
      - ENABLE_JVB_XMPP_SERVER
      - ENABLE_OCTO
      - ENABLE_OCTO_SCTP
      - ENABLE_RECORDING
      - ENABLE_SCTP
      - ENABLE_VISITORS
      - ENABLE_AUTO_LOGIN
      - JICOFO_AUTH_LIFETIME
      - JICOFO_AUTH_PASSWORD
      - JICOFO_AUTH_TYPE
      - JICOFO_BRIDGE_REGION_GROUPS
      - JICOFO_ENABLE_AUTH
      - JICOFO_ENABLE_BRIDGE_HEALTH_CHECKS
      - JICOFO_CONF_INITIAL_PARTICIPANT_WAIT_TIMEOUT
      - JICOFO_CONF_SINGLE_PARTICIPANT_TIMEOUT
      - JICOFO_CONF_SOURCE_SIGNALING_DELAYS
      - JICOFO_CONF_MAX_AUDIO_SENDERS
      - JICOFO_CONF_MAX_VIDEO_SENDERS
      - JICOFO_CONF_STRIP_SIMULCAST
      - JICOFO_CONF_SSRC_REWRITING
      - JICOFO_ENABLE_HEALTH_CHECKS
      - JICOFO_ENABLE_REST
      - JICOFO_HEALTH_CHECKS_USE_PRESENCE
      - JICOFO_MAX_MEMORY
      - JICOFO_MULTI_STREAM_BACKWARD_COMPAT
      - JICOFO_OCTO_REGION
      - JICOFO_TRUSTED_DOMAINS
      - JIBRI_BREWERY_MUC
      - JIBRI_REQUEST_RETRIES
      - JIBRI_PENDING_TIMEOUT
      - JIGASI_BREWERY_MUC
      - JIGASI_SIP_URI
      - JVB_BREWERY_MUC
      - JVB_XMPP_AUTH_DOMAIN
      - JVB_XMPP_INTERNAL_MUC_DOMAIN
      - JVB_XMPP_PORT
      - JVB_XMPP_SERVER
      - MAX_BRIDGE_PARTICIPANTS
      - OCTO_BRIDGE_SELECTION_STRATEGY
      - PROSODY_VISITORS_MUC_PREFIX
      - SENTRY_DSN="${JICOFO_SENTRY_DSN:-0}"
      - SENTRY_ENVIRONMENT
      - SENTRY_RELEASE
      - TZ
      - VISITORS_MAX_PARTICIPANTS
      - VISITORS_MAX_VISITORS_PER_NODE
      - VISITORS_XMPP_AUTH_DOMAIN
      - VISITORS_XMPP_SERVER
      - VISITORS_XMPP_DOMAIN
      - XMPP_DOMAIN
      - XMPP_AUTH_DOMAIN
      - XMPP_INTERNAL_MUC_DOMAIN
      - XMPP_MUC_DOMAIN
      - XMPP_RECORDER_DOMAIN
      - XMPP_SERVER
      - XMPP_PORT
      - MAX_SSRCS_PER_USER
      - MAX_SSRC_GROUPS_PER_USER
    depends_on:
      - prosody
    networks:
      - confomeetnet

  jvb:
    image: jitsi/jvb:${JITSI_IMAGE_VERSION:-stable-9364-1}
    restart: ${RESTART_POLICY:-unless-stopped}
    ports:
      - '${JVB_PORT:-10000}:${JVB_PORT:-10000}/udp'
      - '127.0.0.1:${JVB_COLIBRI_PORT:-8080}:8080'
    volumes:
      - ${CONFIG}/jvb:/config:Z
    environment:
      - AUTOSCALER_SIDECAR_KEY_FILE
      - AUTOSCALER_SIDECAR_KEY_ID
      - AUTOSCALER_SIDECAR_GROUP_NAME
      - AUTOSCALER_SIDECAR_HOST_ID
      - AUTOSCALER_SIDECAR_INSTANCE_ID
      - AUTOSCALER_SIDECAR_PORT
      - AUTOSCALER_SIDECAR_REGION
      - AUTOSCALER_SIDECAR_SHUTDOWN_POLLING_INTERVAL
      - AUTOSCALER_SIDECAR_STATS_POLLING_INTERVAL
      - DOCKER_HOST_ADDRESS
      - ENABLE_COLIBRI_WEBSOCKET
      - ENABLE_JVB_XMPP_SERVER
      - ENABLE_OCTO
      - JVB_ADVERTISE_IPS
      - JVB_ADVERTISE_PRIVATE_CANDIDATES
      - JVB_AUTH_USER
      - JVB_AUTH_PASSWORD
      - JVB_BREWERY_MUC
      - JVB_DISABLE_STUN
      - JVB_INSTANCE_ID
      - JVB_PORT
      - JVB_MUC_NICKNAME
      - JVB_STUN_SERVERS
      - JVB_LOG_FILE
      - JVB_OCTO_BIND_ADDRESS
      - JVB_OCTO_REGION
      - JVB_OCTO_RELAY_ID
      - JVB_REQUIRE_VALID_ADDRESS
      - JVB_WS_DOMAIN
      - JVB_WS_SERVER_ID
      - JVB_XMPP_AUTH_DOMAIN
      - JVB_XMPP_INTERNAL_MUC_DOMAIN
      - JVB_XMPP_PORT
      - JVB_XMPP_SERVER
      - PUBLIC_URL
      - SENTRY_DSN="${JVB_SENTRY_DSN:-0}"
      - SENTRY_ENVIRONMENT
      - SENTRY_RELEASE
      - COLIBRI_REST_ENABLED
      - SHUTDOWN_REST_ENABLED
      - TZ
      - VIDEOBRIDGE_MAX_MEMORY
      - XMPP_AUTH_DOMAIN
      - XMPP_INTERNAL_MUC_DOMAIN
      - XMPP_SERVER
      - XMPP_PORT
    depends_on:
      - prosody
    networks:
      - confomeetnet

  nginx:
    build:
      context: ./nginx
      dockerfile: ./Dockerfile
      args:
        XMPP_DOMAIN: ${XMPP_DOMAIN}
        ADMIN_FRONTEND_GIT_USER: ${ADMIN_FRONTEND_GIT_USER}
        ADMIN_FRONTEND_GIT_PASS: ${ADMIN_FRONTEND_GIT_PASS}
        ADMIN_FRONTEND_BRANCH: ${ADMIN_FRONTEND_BRANCH}
        CCMS_BASE_URL: ${CCMS_BASE_URL}
    depends_on:
      - admin_backend
      - jicofo
      - prosody
      - etherpad
      - whiteboard
    ports:
      - '80:80'
      - '443:443'
    networks:
      - confomeetnet
    restart: unless-stopped
    volumes:
      - ./volume/jibri:/config

  prosody:
    image: jitsi/prosody:${JITSI_IMAGE_VERSION:-stable-9364-1}
    restart: ${RESTART_POLICY:-unless-stopped}
    expose:
      - '${XMPP_PORT:-5222}'
      - '${PROSODY_S2S_PORT:-5269}'
      - '5347'
      - '${PROSODY_HTTP_PORT:-5280}'
    ports:
      - "5222:5222/tcp"
      - "5280:5280/tcp"
    volumes:
      - ${CONFIG}/prosody/config:/config:Z
      - ./prosody/prosody-plugins-custom:/prosody-plugins-custom:ro
    environment:
      - AUTH_TYPE
      - DISABLE_POLLS
      - ENABLE_AUTH
      - ENABLE_AV_MODERATION
      - ENABLE_BREAKOUT_ROOMS
      - ENABLE_END_CONFERENCE
      - ENABLE_GUESTS
      - ENABLE_IPV6
      - ENABLE_LOBBY
      - ENABLE_RECORDING
      - ENABLE_S2S
      - ENABLE_VISITORS
      - ENABLE_XMPP_WEBSOCKET
      - ENABLE_JAAS_COMPONENTS
      - GC_TYPE
      - GC_INC_TH
      - GC_INC_SPEED
      - GC_INC_STEP_SIZE
      - GC_GEN_MIN_TH
      - GC_GEN_MAX_TH
      - GLOBAL_CONFIG
      - GLOBAL_MODULES
      - JIBRI_RECORDER_USER
      - JIBRI_RECORDER_PASSWORD
      - JIBRI_SIP_BREWERY_MUC
      - JIBRI_XMPP_USER
      - JIBRI_XMPP_PASSWORD
      - JICOFO_AUTH_PASSWORD
      - JICOFO_COMPONENT_SECRET
      - JIGASI_XMPP_USER
      - JIGASI_XMPP_PASSWORD
      - JVB_AUTH_USER
      - JVB_AUTH_PASSWORD
      - JWT_APP_ID
      - JWT_APP_SECRET
      - JWT_ACCEPTED_ISSUERS
      - JWT_ACCEPTED_AUDIENCES
      - JWT_ASAP_KEYSERVER
      - JWT_ALLOW_EMPTY
      - JWT_AUTH_TYPE
      - JWT_ENABLE_DOMAIN_VERIFICATION
      - JWT_TOKEN_AUTH_MODULE
      - MATRIX_UVS_URL
      - MATRIX_UVS_ISSUER
      - MATRIX_UVS_AUTH_TOKEN
      - MATRIX_UVS_SYNC_POWER_LEVELS
      - MATRIX_LOBBY_BYPASS
      - LOG_LEVEL
      - LDAP_AUTH_METHOD
      - LDAP_BASE
      - LDAP_BINDDN
      - LDAP_BINDPW
      - LDAP_FILTER
      - LDAP_VERSION
      - LDAP_TLS_CIPHERS
      - LDAP_TLS_CHECK_PEER
      - LDAP_TLS_CACERT_FILE
      - LDAP_TLS_CACERT_DIR
      - LDAP_START_TLS
      - LDAP_URL
      - LDAP_USE_TLS
      - MAX_PARTICIPANTS
      - PROSODY_ADMINS
      - PROSODY_AUTH_TYPE
      - PROSODY_C2S_LIMIT
      - PROSODY_C2S_REQUIRE_ENCRYPTION
      - PROSODY_RESERVATION_ENABLED
      - PROSODY_RESERVATION_REST_BASE_URL
      - PROSODY_ENABLE_RATE_LIMITS
      - PROSODY_ENABLE_S2S
      - PROSODY_GUEST_AUTH_TYPE
      - PROSODY_HTTP_PORT
      - PROSODY_LOG_CONFIG
      - PROSODY_MODE
      - PROSODY_RATE_LIMIT_LOGIN_RATE
      - PROSODY_RATE_LIMIT_SESSION_RATE
      - PROSODY_RATE_LIMIT_TIMEOUT
      - PROSODY_RATE_LIMIT_ALLOW_RANGES
      - PROSODY_RATE_LIMIT_CACHE_SIZE
      - PROSODY_S2S_LIMIT
      - PROSODY_S2S_PORT
      - PROSODY_TRUSTED_PROXIES
      - PROSODY_VISITOR_INDEX
      - PROSODY_VISITORS_MUC_PREFIX
      - PUBLIC_URL
      - STUN_HOST
      - STUN_PORT
      - TURN_CREDENTIALS
      - TURN_HOST
      - TURNS_HOST
      - TURN_PORT
      - TURNS_PORT
      - TURN_TRANSPORT
      - TZ
      - VISITORS_MAX_VISITORS_PER_NODE
      - VISITORS_XMPP_DOMAIN
      - VISITORS_XMPP_SERVER
      - VISITORS_XMPP_PORT
      - XMPP_BREAKOUT_MUC_MODULES
      - XMPP_CONFIGURATION
      - XMPP_DOMAIN
      - XMPP_AUTH_DOMAIN
      - XMPP_GUEST_DOMAIN
      - XMPP_MUC_DOMAIN
      - XMPP_INTERNAL_MUC_DOMAIN
      - XMPP_LOBBY_MUC_MODULES
      - XMPP_MODULES
      - XMPP_MUC_MODULES
      - XMPP_MUC_CONFIGURATION
      - XMPP_INTERNAL_MUC_MODULES
      - XMPP_RECORDER_DOMAIN
      - XMPP_PORT
      - XMPP_SERVER_S2S_PORT
      - XMPP_SPEAKERSTATS_MODULES
    networks:
      confomeetnet:
        aliases:
          - ${XMPP_SERVER:-xmpp.meet.jitsi}

  whiteboard:
    build:
      context: ./excalidraw-backend
      dockerfile: ./Dockerfile
    restart: unless-stopped
    #ports:
      #- 9091
      #- 3002
    depends_on:
      - prosody
    networks:
      - confomeetnet

networks:
  confomeetnet:
    driver: bridge
