version: '3.7'

services:
  admin_backend:
    build:
      context: ./admin_backend
      dockerfile: ./Dockerfile
      args:
        ADMIN_FRONTEND_GIT_USER: ${ADMIN_FRONTEND_GIT_USER}
        ADMIN_FRONTEND_GIT_PASS: ${ADMIN_FRONTEND_GIT_PASS}
        ADMIN_BACKEND_BRANCH: ${ADMIN_BACKEND_BRANCH}
      #ports:
        #- '8081:80'
    environment:
      ConnectionStrings__DbConnection: ${ADMIN_DB_CONNECTION_STRING}
      Schema: ${ADMIN_DB_SCHEMA}
      DocumentStorage: ${ADMIN_DOCUMENT_STORAGE}
      Meeting__secret: ${PROSODY_APP_SECRET}
      Meeting__iss: ${ADMIN_MEETING_ISS}
      Meeting__aud: ${ADMIN_MEETING_AUD}
      Meeting__host: https://${XMPP_DOMAIN}
      Meeting__sub: ${XMPP_DOMAIN}
      Jwt__Key: ${ADMIN_JWT_KEY}
      Jwt__Issuer: ${ADMIN_JWT_ISSUER}
      Jwt__Audience: ${ADMIN_JWT_AUDIENCE}
      Jwt__TokenInMinutes: ${ADMIN_JWT_TOKENINMINUTES}
      ChannelMailFirstSetting__Mail: ${ADMIN_MAIL_MAIL}
      ChannelMailFirstSetting__DisplayName: ${ADMIN_MAIL_DISPLAYNAME}
      ChannelMailFirstSetting__Password: ${ADMIN_MAIL_PASSWORD}
      ChannelMailFirstSetting__Host: ${ADMIN_MAIL_HOST}
      ChannelMailFirstSetting__Port: ${ADMIN_MAIL_PORT}
      GoogleReCaptchaSecretKey__SecretKey: ${ADMIN_CAPTCHA_SECRET_KEY}
      PassworLifetimeDays: ${ADMIN_PASSWORD_LIFE_TIME_DAYS}
      LockedTempTimeInMinutes: ${ADMIN_LOCKED_TEMP_TIME_IN_MINUTES}
      CurrentHostName: ${ADMIN_CURRENT_HOST_NAME}
      EnableRegistration: ${ADMIN_ENABLE_REGISTRATION}
      EnableOnlyAdminLogin: ${ADMIN_ENABLE_ONLAY_ADMIN_LOGIN}
      ProsodyDomain: ${CONFERENCE_PROSODY_DOMAIN}
      OtpPeriodInMinutes: ${ADMIN_OTP_PERIOD_IN_MINUTES}
      DisableActivate: ${ADMIN_DISABLE_ACTIVE}
      YandexDisk__DebugToken: ${YANDEX_DISK_DEBUG_TOKEN}
      ASPNETCORE_HTTP_PORTS: "5000"
      CONFOMEET_S3_URL: ${CONFOMEET_S3_URL}
      CONFOMEET_S3_URL_OVERRIDE_FOR_AWS_SDK: ${CONFOMEET_S3_URL_OVERRIDE_FOR_AWS_SDK}
      CONFOMEET_S3_CLIENT_ID: ${CONFOMEET_S3_CLIENT_ID}
      CONFOMEET_S3_CLIENT_SECRET: ${CONFOMEET_S3_CLIENT_SECRET}
      CONFOMEET_S3_REGION: ${CONFOMEET_S3_REGION}
      oidc__authority: ${OIDC_AUTHORITY}
      oidc__client_id: ${OIDC_CLIENT_ID}
    networks:
      - confomeetnet
    restart: unless-stopped
    volumes:
      - ./volume/jibri:/config

  etherpad:
    build:
      context: ./etherpad
      dockerfile: ./Dockerfile
    environment:
        - TITLE=${ETHERPAD_TITLE}
        - DEFAULT_PAD_TEXT=${ETHERPAD_DEFAULT_PAD_TEXT}
        - SKIN_NAME=${ETHERPAD_SKIN_NAME}
        - SKIN_VARIANTS=${ETHERPAD_SKIN_VARIANTS}
    restart: unless-stopped
    depends_on:
      - prosody
    #ports:
      #- 9001
    networks:
      - confomeetnet

  jicofo:
    build:
      context: ./jicofo
      dockerfile: ./Dockerfile
      args:
        XMPP_DOMAIN: ${XMPP_DOMAIN}
        TZ: ${TZ}
        JICOFO_AUTH_PASSWORD: ${JICOFO_AUTH_PASSWORD}
    depends_on:
      - prosody
    networks:
      - confomeetnet
    restart: unless-stopped

  jvb:
    build:
      context: ./jvb
      dockerfile: ./Dockerfile
      args:
        JVB_PORT: ${JVB_PORT}
        XMPP_DOMAIN: ${XMPP_DOMAIN}
        JVB_USERNAME: ${JVB_USERNAME}
        JVB_MUC_NICKNAME: ${JVB_MUC_NICKNAME}
        JVB_AUTH_NAME: ${JVB_AUTH_NAME}
        JVB_AUTH_PASS: ${JVB_AUTH_PASSWORD}
        JVB_LOCAL_ADDRESS: ${JVB_LOCAL_ADDRESS}
        JVB_PUBLIC_ADDRESS: ${JVB_PUBLIC_ADDRESS}
        STUN_ADDRESSES: ${STUN_ADDRESSES}
    network_mode: host
    restart: unless-stopped

  nginx:
    build:
      context: ./nginx
      dockerfile: ./Dockerfile
      args:
        XMPP_DOMAIN: ${XMPP_DOMAIN}
        ADMIN_FRONTEND_GIT_USER: ${ADMIN_FRONTEND_GIT_USER}
        ADMIN_FRONTEND_GIT_PASS: ${ADMIN_FRONTEND_GIT_PASS}
        ADMIN_FRONTEND_BRANCH: ${ADMIN_FRONTEND_BRANCH}
        CCMS_BASE_URL: ${CCMS_BASE_URL}
    depends_on:
      - admin_backend
      - jicofo
      - prosody
      - etherpad
      - whiteboard
    ports:
      - '80:80'
      - '443:443'
    networks:
      - confomeetnet
    restart: unless-stopped
    volumes:
      - ./volume/jibri:/config

  prosody:
    build:
      context: ./prosody
      dockerfile: ./Dockerfile
      args:
        XMPP_DOMAIN: ${XMPP_DOMAIN}
        PROSODY_APP_ID: ${PROSODY_APP_ID}
        PROSODY_APP_SECRET: ${PROSODY_APP_SECRET}
        JICOFO_AUTH_PASSWORD: ${JICOFO_AUTH_PASSWORD}
        JVB_USERNAME: ${JVB_USERNAME}
        JVB_AUTH_PASS: ${JVB_AUTH_PASS}
        JIBRI_RECORDER_PASSWORD: ${JIBRI_RECORDER_PASSWORD}
        JIBRI_XMPP_PASSWORD: ${JIBRI_XMPP_PASSWORD}
        JIGASI_XMPP_USER: ${JIGASI_XMPP_USER}
        JIGASI_XMPP_PASSWORD: ${JIGASI_XMPP_PASSWORD}

    extra_hosts:
      - '${XMPP_DOMAIN}:127.0.0.1'
    #volumes:
      #- ./log:/var/log/prosody
    networks:
      - confomeetnet
    ports:
      - '5222:5222'
      - '5280:5280'
    restart: unless-stopped

  whiteboard:
    build:
      context: ./excalidraw-backend
      dockerfile: ./Dockerfile
    restart: unless-stopped
    #ports:
      #- 9091
      #- 3002
    depends_on:
      - prosody
    networks:
      - confomeetnet

networks:
  confomeetnet:
    driver: bridge
