version: '3'

services:
  jvb:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        JVB_PORT: ${JVB_PORT}
        XMPP_HOSTNAME: ${XMPP_HOSTNAME}
        JVB_USERNAME: ${JVB_USERNAME}
        JVB_MUC_NICKNAME: ${JVB_MUC_NICKNAME}
        JVB_AUTH_NAME: ${JVB_AUTH_NAME}
        JVB_AUTH_PASS: ${JVB_AUTH_PASS}
        JVB_LOCAL_ADDRESS: ${JVB_LOCAL_ADDRESS}
        JVB_PUBLIC_ADDRESS: ${JVB_PUBLIC_ADDRESS}
        STUN_ADDRESSES: ${STUN_ADDRESSES}
    #ports:
      #- '${JVB_PORT}:${JVB_PORT}/udp'
    extra_hosts:
      - '${XMPP_HOSTNAME}:${XMPP_IP}'
    restart: unless-stopped
    network_mode: host
    #networks:
      #- jitsinet

#networks:
  #jitsinet:
    #driver: bridge
